### ISSUE TITLE
Crash on iOS 13

### ISSUE THREAD

**Issue by MR-yo** [tanersener/ffmpeg-kit-test#18]
**Environment:**

* Platform: iOS
* Device: iPhone7-13.3.1 / iPhone6s-13.6
* Version: ffmpeg-kit-ios-full 4.5.1
* Xcode version: 12.5.1
* Cocoapods version: 1.10.1

---

**Xcode log:**

dyld: Library not loaded: /usr/lib/libexpat.1.dylib
  Referenced from: /private/var/containers/Bundle/Application/F447589E-2C1F-47C6-B5B1-397F21CB8F3B/FFmpegKitIOS.app/Frameworks/libavdevice.framework/libavdevice
  Reason: image not found
dyld: launch, loading dependent libraries
DYLD_LIBRARY_PATH=/usr/lib/system/introspection
DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib
Message from debugger: Terminated due to signal 6

**Comment by tanersener** [comment]
I don't have enough information to make a comment about this. 

I don't see which test application is used, which source branch is used, where are `ffmpeg-kit` binaries coming from?

**Comment by MR-yo** [comment]
sorry for not gave enough information.

* Branch: main
* Test application: ffmpeg-kit-test-main/ios/test-app-cocoapods

**Steps:**
1. open `Terminal`
2. cd `project path`
3. run `pod install`
4. use `Xcode` open `FFmpegKitIOS.xcworkspace`
5. choose `Device iPhone7-13.3.1` or `iOS simulator iPhone11-13.5`
6. click `run` then crash happened

**Comment by tanersener** [comment]
Thanks, I managed to see the error. I need some time to investigate this.

**Comment by tanersener** [comment]
I patched Apple platform releases `v4.5.1` and `v4.5.1.LTS` with the fix for this issue.

Please clean you `pod cache` and run `pod install` again.

```
pod cache clean ffmpeg-kit-tvos-full
```

**Comment by MR-yo** [comment]
It works. Cooooool !

**Comment by tanersener** [comment]
Great! Closing the issue. Let us know if you encounter another problem.
