### ISSUE TITLE
How to build ffmpeg-kit-test

### ISSUE THREAD

**Issue by mikeabernathy** [tanersener/ffmpeg-kit-test#2]
Thank you for doing this exceptional work.

I have downloaded the appropriate ffmpeg-kit for my plans (macOS full), but I would like to build the ffmpeg-kit-test using these libs.  

Might you give us a little more detail about how to do that?  
For example, what should the folder structure be?  Where is Xcode expecting to find the frameworks?

Again, thank you for all the work you did in creating this excellent packaging of FFMPEG.

**Comment by tanersener** [comment]
For Apple platforms (iOS, macOS, tvOS), you need to open the `xcworkspace` directory in `Xcode` to build a project.

- For test apps that use `cocoapods` you also need to run `pod install`
- For test apps with local dependency you must copy `frameworks` to the project directory e.g. `macos/test-app-local-dependency`

**Comment by mikeabernathy** [comment]
Many thanks!
