### ISSUE TITLE
On Import Getting Error

### ISSUE THREAD

**Issue by Kiru3014** [tanersener/ffmpeg-kit-test#24]
Hi When i run android Project getting following error 

Null extracted folder for artifact: ResolvedArtifact(componentIdentifier=ffmpeg-kit.aar, variantName=null, artifactFile=C:\Users\Arspectra\Desktop\Arsofin_Ar_App\ffmpeg-kit\prebuilt\bundle-android-aar\ffmpeg-kit\ffmpeg-kit.aar, extractedFolder=null, dependencyType=ANDROID, isWrappedModule=false, buildMapping={__current_build__=C:\Users\Arspectra\Desktop\Arsofin_Ar_App\ffmpeg-kit-test-main\android}, mavenCoordinatesCache=com.android.build.gradle.internal.ide.dependencies.MavenCoordinatesCacheBuildService$Inject@c66e5cf)

**Comment by tanersener** [comment]
`test-app-local-dependency` for Android is configured to load a local `.aar` file by default. That's what the local dependency means. See the [build.gradle](https://github.com/tanersener/ffmpeg-kit-test/blob/main/android/test-app-local-dependency/build.gradle#L55).

Disable the `test-app-local-dependency` from [settings.gradle](https://github.com/tanersener/ffmpeg-kit-test/blob/main/android/settings.gradle#L1) if you don't have it.
