### ISSUE TITLE
Requesting REQUEST_EXTERNAL_STORAGE if Camera permissions are missing

### ISSUE THREAD

**Issue by 4thel00z** [tanersener/ffmpeg-kit-test#3]
Don't know much android but this looks wrong:

https://github.com/tanersener/ffmpeg-kit-test/blob/3c2fa0adb0972489da28c0bf6220714e2008184c/android/test-app-maven-central/src/main/java/com/arthenica/ffmpegkit/test/MainActivity.java#L143

**Comment by tanersener** [comment]
`REQUEST_EXTERNAL_STORAGE` is an application specific request code. It is not used actively. However, I agree that the name of the constant is misleading a tad. So, I renamed it as `REQUEST_PERMISSIONS` in the [new version](https://github.com/tanersener/ffmpeg-kit-test/blob/main/android/test-app-maven-central/src/main/java/com/arthenica/ffmpegkit/test/MainActivity.java#L143).

**Comment by 4thel00z** [comment]
thx boi
