### ISSUE TITLE
Unknown encoder 'libx264'

### ISSUE THREAD

**Issue by VanHop94** [tanersener/ffmpeg-kit-test#32]
When opening test app and click Video tab, select x264 this message will show in log:
Unknown encoder 'libx264'

Similar to: x265, openh264,...

I tested on my device: Samsung Galaxy Note 10+, Android Version: 12

Please help me to check

**Comment by tanersener** [comment]
Have a look at [Packages](https://github.com/tanersener/ffmpeg-kit#8-packages) section. See which packages include `libx264` and make sure that your `build.gradle` depends on that `ffmpeg-kit` package.

**Comment by VanHop94** [comment]
Hi @tanersener thank you for reply quickly. But i use this package: implementation 'com.arthenica:ffmpeg-kit-full:4.5.1-1.LTS'. I just  clone this project and run on my phone, don't make any change. And it doesn't work

**Comment by VanHop94** [comment]
> Have a look at the [Packages](https://github.com/tanersener/ffmpeg-kit#8-packages) section. See which packages include `libx264` and make sure that your `build.gradle` depends on that `ffmpeg-kit` package.

Thank you for your reply quickly. It works now
